/* This file was generated by qmake with the info from <root>/src/multimediawidgets/multimediawidgets.pro. */
#ifndef QT_QTMULTIMEDIAWIDGETS_VERSION_H
#define QT_QTMULTIMEDIAWIDGETS_VERSION_H
#define QTMULTIMEDIAWIDGETS_VERSION_STR "5.0.2"
#define QTMULTIMEDIAWIDGETS_VERSION 0x050002
#endif // QT_QTMULTIMEDIAWIDGETS_VERSION_H
