/* This file was generated by qmake with the info from <root>/src/assistant/clucene/clucene.pro. */
#ifndef QT_QTCLUCENE_VERSION_H
#define QT_QTCLUCENE_VERSION_H
#define QTCLUCENE_VERSION_STR "5.0.2"
#define QTCLUCENE_VERSION 0x050002
#endif // QT_QTCLUCENE_VERSION_H
