/* This file was generated by qmake with the info from <root>/widgetsapi.pri. */
#ifndef QT_QTWEBKITWIDGETS_VERSION_H
#define QT_QTWEBKITWIDGETS_VERSION_H
#define QTWEBKITWIDGETS_VERSION_STR "5.0.2"
#define QTWEBKITWIDGETS_VERSION 0x050002
#endif // QT_QTWEBKITWIDGETS_VERSION_H
