/* This file was generated by qmake with the info from <root>/src/multimedia/multimedia.pro. */
#ifndef QT_QTMULTIMEDIA_VERSION_H
#define QT_QTMULTIMEDIA_VERSION_H
#define QTMULTIMEDIA_VERSION_STR "5.0.2"
#define QTMULTIMEDIA_VERSION 0x050002
#endif // QT_QTMULTIMEDIA_VERSION_H
