/* This file was generated by qmake with the info from <root>/src/particles/particles.pro. */
#ifndef QT_QTQUICKPARTICLES_VERSION_H
#define QT_QTQUICKPARTICLES_VERSION_H
#define QTQUICKPARTICLES_VERSION_STR "5.0.2"
#define QTQUICKPARTICLES_VERSION 0x050002
#endif // QT_QTQUICKPARTICLES_VERSION_H
