/* This file was generated by qmake with the info from <root>/src/xmlpatterns/xmlpatterns.pro. */
#ifndef QT_QTXMLPATTERNS_VERSION_H
#define QT_QTXMLPATTERNS_VERSION_H
#define QTXMLPATTERNS_VERSION_STR "5.0.2"
#define QTXMLPATTERNS_VERSION 0x050002
#endif // QT_QTXMLPATTERNS_VERSION_H
