/* This file was generated by qmake with the info from <root>/src/dbus/dbus.pro. */
#ifndef QT_QTDBUS_VERSION_H
#define QT_QTDBUS_VERSION_H
#define QTDBUS_VERSION_STR "5.0.2"
#define QTDBUS_VERSION 0x050002
#endif // QT_QTDBUS_VERSION_H
