/* This file was generated by qmake with the info from <root>/src/testlib/testlib.pro. */
#ifndef QT_QTTEST_VERSION_H
#define QT_QTTEST_VERSION_H
#define QTTEST_VERSION_STR "5.0.2"
#define QTTEST_VERSION 0x050002
#endif // QT_QTTEST_VERSION_H
