/* This file was generated by qmake with the info from <root>/src/designer/src/components/lib/lib.pro. */
#ifndef QT_QTDESIGNERCOMPONENTS_VERSION_H
#define QT_QTDESIGNERCOMPONENTS_VERSION_H
#define QTDESIGNERCOMPONENTS_VERSION_STR "5.0.2"
#define QTDESIGNERCOMPONENTS_VERSION 0x050002
#endif // QT_QTDESIGNERCOMPONENTS_VERSION_H
