/* This file was generated by qmake with the info from <root>/src/declarative/declarative.pro. */
#ifndef QT_QTDECLARATIVE_VERSION_H
#define QT_QTDECLARATIVE_VERSION_H
#define QTDECLARATIVE_VERSION_STR "5.0.2"
#define QTDECLARATIVE_VERSION 0x050002
#endif // QT_QTDECLARATIVE_VERSION_H
