/* This file was generated by qmake with the info from <root>/src/platformsupport/platformsupport.pro. */
#ifndef QT_QTPLATFORMSUPPORT_VERSION_H
#define QT_QTPLATFORMSUPPORT_VERSION_H
#define QTPLATFORMSUPPORT_VERSION_STR "5.0.2"
#define QTPLATFORMSUPPORT_VERSION 0x050002
#endif // QT_QTPLATFORMSUPPORT_VERSION_H
