/* This file was generated by qmake with the info from <root>/src/qtmultimediaquicktools/qtmultimediaquicktools.pro. */
#ifndef QT_QTMULTIMEDIAQUICK_P_VERSION_H
#define QT_QTMULTIMEDIAQUICK_P_VERSION_H
#define QTMULTIMEDIAQUICK_P_VERSION_STR "5.0.2"
#define QTMULTIMEDIAQUICK_P_VERSION 0x050002
#endif // QT_QTMULTIMEDIAQUICK_P_VERSION_H
