/* This file was generated by qmake with the info from <root>/src/quick/quick.pro. */
#ifndef QT_QTQUICK_VERSION_H
#define QT_QTQUICK_VERSION_H
#define QTQUICK_VERSION_STR "5.0.2"
#define QTQUICK_VERSION 0x050002
#endif // QT_QTQUICK_VERSION_H
