/* This file was generated by qmake with the info from <root>/src/scripttools/scripttools.pro. */
#ifndef QT_QTSCRIPTTOOLS_VERSION_H
#define QT_QTSCRIPTTOOLS_VERSION_H
#define QTSCRIPTTOOLS_VERSION_STR "5.0.2"
#define QTSCRIPTTOOLS_VERSION 0x050002
#endif // QT_QTSCRIPTTOOLS_VERSION_H
