/* This file was generated by qmake with the info from <root>/src/gui/gui.pro. */
#ifndef QT_QTGUI_VERSION_H
#define QT_QTGUI_VERSION_H
#define QTGUI_VERSION_STR "5.0.2"
#define QTGUI_VERSION 0x050002
#endif // QT_QTGUI_VERSION_H
