/* This file was generated by qmake with the info from <root>/src/qmltest/qmltest.pro. */
#ifndef QT_QTQUICKTEST_VERSION_H
#define QT_QTQUICKTEST_VERSION_H
#define QTQUICKTEST_VERSION_STR "5.0.2"
#define QTQUICKTEST_VERSION 0x050002
#endif // QT_QTQUICKTEST_VERSION_H
