/* This file was generated by qmake with the info from <root>/src/designer/src/lib/lib.pro. */
#ifndef QT_QTDESIGNER_VERSION_H
#define QT_QTDESIGNER_VERSION_H
#define QTDESIGNER_VERSION_STR "5.0.2"
#define QTDESIGNER_VERSION 0x050002
#endif // QT_QTDESIGNER_VERSION_H
