/* This file was generated by qmake with the info from <root>/src/v8/v8.pro. */
#ifndef QT_QTV8_VERSION_H
#define QT_QTV8_VERSION_H
#define QTV8_VERSION_STR "5.0.2"
#define QTV8_VERSION 0x050002
#endif // QT_QTV8_VERSION_H
