/* This file was generated by qmake with the info from <root>/src/network/network.pro. */
#ifndef QT_QTNETWORK_VERSION_H
#define QT_QTNETWORK_VERSION_H
#define QTNETWORK_VERSION_STR "5.0.2"
#define QTNETWORK_VERSION 0x050002
#endif // QT_QTNETWORK_VERSION_H
