/* This file was generated by qmake with the info from <root>/src/concurrent/concurrent.pro. */
#ifndef QT_QTCONCURRENT_VERSION_H
#define QT_QTCONCURRENT_VERSION_H
#define QTCONCURRENT_VERSION_STR "5.0.2"
#define QTCONCURRENT_VERSION 0x050002
#endif // QT_QTCONCURRENT_VERSION_H
