/* This file was generated by qmake with the info from <root>/src/sql/sql.pro. */
#ifndef QT_QTSQL_VERSION_H
#define QT_QTSQL_VERSION_H
#define QTSQL_VERSION_STR "5.0.2"
#define QTSQL_VERSION 0x050002
#endif // QT_QTSQL_VERSION_H
