/* This file was generated by qmake with the info from <root>/src/qml/qml.pro. */
#ifndef QT_QTQML_VERSION_H
#define QT_QTQML_VERSION_H
#define QTQML_VERSION_STR "5.0.2"
#define QTQML_VERSION 0x050002
#endif // QT_QTQML_VERSION_H
