/* This file was generated by qmake with the info from <root>/src/printsupport/printsupport.pro. */
#ifndef QT_QTPRINTSUPPORT_VERSION_H
#define QT_QTPRINTSUPPORT_VERSION_H
#define QTPRINTSUPPORT_VERSION_STR "5.0.2"
#define QTPRINTSUPPORT_VERSION 0x050002
#endif // QT_QTPRINTSUPPORT_VERSION_H
