/* This file was generated by qmake with the info from <root>/api.pri. */
#ifndef QT_QTWEBKIT_VERSION_H
#define QT_QTWEBKIT_VERSION_H
#define QTWEBKIT_VERSION_STR "5.0.2"
#define QTWEBKIT_VERSION 0x050002
#endif // QT_QTWEBKIT_VERSION_H
