/* This file was generated by qmake with the info from <root>/src/opengl/opengl.pro. */
#ifndef QT_QTOPENGL_VERSION_H
#define QT_QTOPENGL_VERSION_H
#define QTOPENGL_VERSION_STR "5.0.2"
#define QTOPENGL_VERSION 0x050002
#endif // QT_QTOPENGL_VERSION_H
