/* This file was generated by qmake with the info from <root>/src/assistant/help/help.pro. */
#ifndef QT_QTHELP_VERSION_H
#define QT_QTHELP_VERSION_H
#define QTHELP_VERSION_STR "5.0.2"
#define QTHELP_VERSION 0x050002
#endif // QT_QTHELP_VERSION_H
