/* This file was generated by qmake with the info from <root>/src/script/script.pro. */
#ifndef QT_QTSCRIPT_VERSION_H
#define QT_QTSCRIPT_VERSION_H
#define QTSCRIPT_VERSION_STR "5.0.2"
#define QTSCRIPT_VERSION 0x050002
#endif // QT_QTSCRIPT_VERSION_H
