/* This file was generated by qmake with the info from <root>/src/svg/svg.pro. */
#ifndef QT_QTSVG_VERSION_H
#define QT_QTSVG_VERSION_H
#define QTSVG_VERSION_STR "5.0.2"
#define QTSVG_VERSION 0x050002
#endif // QT_QTSVG_VERSION_H
