/* This file was generated by qmake with the info from <root>/src/qmldevtools/qmldevtools.pro. */
#ifndef QT_QTQMLDEVTOOLS_VERSION_H
#define QT_QTQMLDEVTOOLS_VERSION_H
#define QTQMLDEVTOOLS_VERSION_STR "5.0.2"
#define QTQMLDEVTOOLS_VERSION 0x050002
#endif // QT_QTQMLDEVTOOLS_VERSION_H
