/* This file was generated by qmake with the info from <root>/src/designer/src/uitools/uitools.pro. */
#ifndef QT_QTUITOOLS_VERSION_H
#define QT_QTUITOOLS_VERSION_H
#define QTUITOOLS_VERSION_STR "5.0.2"
#define QTUITOOLS_VERSION 0x050002
#endif // QT_QTUITOOLS_VERSION_H
