/* This file was generated by qmake with the info from <root>/src/xml/xml.pro. */
#ifndef QT_QTXML_VERSION_H
#define QT_QTXML_VERSION_H
#define QTXML_VERSION_STR "5.0.2"
#define QTXML_VERSION 0x050002
#endif // QT_QTXML_VERSION_H
